// This file is generated by farmEscape SDK project wizard
//
// Application UUID: QdRgFsDtoQ
//

#include <stdint.h>
#include <string>
#include <vector>
#include <memory>
#include <stdlib.h>

#include "AppManager.h"
#include "farmEscape.h"

// ==========================================
// GAME STATE & VARIABLES
// ==========================================

struct Chicken
{
    int x;
    int y;
    int speedX;
    int speedY;
    int currentScreen;
    int wanderTimer; // ms until this chicken picks a new direction on its own
};

// 3 independent chickens — each starts on its own screen with its own personality
Chicken chickens[3] = {
    {60, 100, 4, 3, 0, 2000},   // Screen 0: medium pace
    {120, 120, -5, 4, 1, 1500}, // Screen 1: faster and more erratic
    {180, 80, 3, -2, 2, 2800}   // Screen 2: slow and calm
};

int activeChickens = 1;
bool isSeeded = false;

// 0 = Solid White, 1 = Broken Red Gap, 2 = Patched Blue
int fenceState[3] = {0, 0, 0};
int breakTimer = 0;
int lives = 5;

// Cooldown timer for the twist mechanic
int twistCooldown = 0; 

uint32_t gameTime = 0;

int score = 0;
int scoreTimer = 0;
int currentRound = 1;
int breakInterval = 7000; // Starts much slower now

// ==========================================
// CORE SYSTEM
// ==========================================

void OnInit(Cubios::AppManager &appMgr)
{
    appMgr.SetApplication(new farmEscape, "QdRgFsDtoQ");
}

farmEscape::farmEscape() {}
farmEscape::~farmEscape() {}

// ==========================================
// GAME LOGIC (THE BRAIN)
// ==========================================
void farmEscape::on_Tick(uint32_t currentTime, uint32_t deltaTime)
{
    gameTime = currentTime;

    // Decrease the cooldown timer by deltaTime
    if (twistCooldown > 0)
    {
        twistCooldown -= (int)deltaTime;
    }

    if (lives <= 0)
    {
        return;
    }

    // --- REBALANCED ROUND PROGRESSION ---
    scoreTimer += deltaTime;
    if (scoreTimer >= 1000)
    {
        score += 1;
        scoreTimer = 0;

        // Rounds increase every 25 seconds
        currentRound = (score / 25) + 1;

        // Fences break gradually faster. 
        // Round 1: 7000ms | Round 6: 5000ms | Round 12: 2600ms
        breakInterval = 7000 - ((currentRound - 1) * 400);

        // Cap to ensure it never becomes faster than the player's 2-second cooldown
        if (breakInterval < 2500)
        {
            breakInterval = 2500;
        }
    }
    
    // 1. THE BREAK TIMER
    breakTimer += deltaTime;
    if (breakTimer >= breakInterval)
    {
        breakTimer = 0;

        for (int i = 0; i < 3; i++)
        {
            if (fenceState[i] == 2)
            {
                fenceState[i] = 0;
            }
        }

        // Find all currently safe fences (0)
        int candidates[3];
        int count = 0;
        for (int i = 0; i < 3; i++)
        {
            if (fenceState[i] == 0)
            {
                candidates[count++] = i;
            }
        }

        // --- REBALANCED BREAK CHAOS ---
        if (count > 0)
        {
            int maxToBreak = 1;
            if (currentRound >= 5) maxToBreak = 2; // Double breaks unlock at Round 5
            if (currentRound >= 8) maxToBreak = 3; // Triple breaks unlock at Round 8

            int numToBreak = (rand() % maxToBreak) + 1; 
            
            if (numToBreak > count) 
            {
                numToBreak = count;
            }

            for (int b = 0; b < numToBreak; b++)
            {
                int pickIndex = rand() % count;
                int screenToBreak = candidates[pickIndex];
                
                fenceState[screenToBreak] = 1; // Break it!

                candidates[pickIndex] = candidates[count - 1];
                count--;
            }
        }
    }

    // 2. MOVE THE CHICKEN
    for (int c = 0; c < 3; c++)
    {
        Chicken &ch = chickens[c]; 

        // --- 1. WANDER: Realistic & Scaling Chicken Behavior ---
        ch.wanderTimer -= (int)deltaTime;
        if (ch.wanderTimer <= 0)
        {
            // 30% chance to stop and "peck", 70% chance to walk
            if (rand() % 10 < 3) 
            {
                ch.speedX = 0;
                ch.speedY = 0;
                ch.wanderTimer = 500 + (rand() % 1000); 
            } 
            else 
            {
                // Dynamic speed limit based on round
                // R1-R2: Limit 2 | R3-R5: Limit 3 | R6-R8: Limit 4 | R9+: Limit 5
                int speedLimit = 2 + (currentRound / 3); 
                if (speedLimit > 5) speedLimit = 5;

                // Smoothly choose a new direction, bounded by the current round's limit
                ch.speedX = (rand() % ((speedLimit * 2) + 1)) - speedLimit; 
                ch.speedY = (rand() % (speedLimit + 2)) - 1; // Bias slightly downwards

                ch.wanderTimer = 1000 + (rand() % 2000); // Walk for 1 to 3s
            }
        }

        // --- 2. MOVE ---
        ch.x += ch.speedX;
        ch.y += ch.speedY;

        // --- 3. SCREEN HOPPING (Contiguous Farm) ---
        if (ch.x > 240)
        {
            ch.x = 0;
            ch.currentScreen = (ch.currentScreen + 1) % 3; 
        }
        else if (ch.x < 0)
        {
            ch.x = 240;
            ch.currentScreen = (ch.currentScreen + 2) % 3; // +2 is the same as -1 with modulo 3
        }

        // --- 4. TOP WALL BOUNCE ---
        if (ch.y < 30)
        {
            ch.y = 30;
            ch.speedY = abs(ch.speedY); // Force a gentle downward bounce
            if (ch.speedY == 0) ch.speedY = 2; // Prevent getting stuck on the wall
        }

        // --- 5. BOTTOM ESCAPE ZONE ---
        if (ch.y > 220)
        {
            if (fenceState[ch.currentScreen] == 1) // Broken gap!
            {
                lives -= 1;
                if (lives < 0) lives = 0;

                // Respawn this specific chicken back at the top of its current screen
                ch.y = 50; 
                ch.speedX = (rand() % 5) - 2;
                ch.speedY = 2; // Walk down
                ch.wanderTimer = 1500;
            }
            else // Fence is patched/safe
            {
                ch.y = 220;
                ch.speedY = -abs(ch.speedY); // Bounce back up safely
                if (ch.speedY == 0) ch.speedY = -2;
            }
        }
    }
}

// ==========================================
// GRAPHICS (THE CAMERA)
// ==========================================
void farmEscape::on_Render(std::array<Cubios::Screen, 3> &screens)
{
    for (auto it = screens.begin(); it != screens.end(); ++it)
    {
        int screenID = it->ID();
        Cubios::GFX_setRenderTarget(screenID);
        Cubios::GFX_clear(Cubios::Gfx::Colors::darkGreen);

        // --- NEW: GLOBAL GAME OVER OVERRIDE ---
        // This overrides everything and forces every screen to show the Game Over state
        if (lives <= 0)
        {
            Cubios::GFX_drawText(120, 100, 8, 0, Cubios::text_align_t::TEXT_ALIGN_CENTER, Cubios::Gfx::Colors::red, "GAME OVER");
            std::string finalScore = "FINAL SCORE: " + std::to_string(score);
            Cubios::GFX_drawText(120, 140, 8, 0, Cubios::text_align_t::TEXT_ALIGN_CENTER, Cubios::Gfx::Colors::cyan, finalScore.c_str());
            Cubios::GFX_drawText(120, 120, 8, 0, Cubios::text_align_t::TEXT_ALIGN_CENTER, Cubios::Gfx::Colors::white, "TAP TO RESTART");
            
            Cubios::GFX_render();
            continue; // CRITICAL: This skips drawing the fences, HUD, and chickens for this screen
        }

        // 1. LIVES HUD
        if (screenID == 0)
        {
            std::string livesStr = "            LIVES: " + std::to_string(lives);
            std::string roundStr = "ROUND: " + std::to_string(currentRound);
            std::string scoreStr = "            SCORE: " + std::to_string(score);

            Cubios::GFX_drawText(10, 15, 8, 0, Cubios::text_align_t::TEXT_ALIGN_CENTER, Cubios::Gfx::Colors::yellow, livesStr.c_str());
            Cubios::GFX_drawText(120, 120, 5, 3, Cubios::text_align_t::TEXT_ALIGN_CENTER, Cubios::Gfx::Colors::black, roundStr.c_str());
            Cubios::GFX_drawText(10, 35, 8, 0, Cubios::text_align_t::TEXT_ALIGN_CENTER, Cubios::Gfx::Colors::cyan, scoreStr.c_str());
        }

        // 2. FARM
        if (screenID == 1)
        {
            Cubios::GFX_drawText(120, 80, 8, 0, Cubios::text_align_t::TEXT_ALIGN_CENTER, Cubios::Gfx::Colors::white, "  /\\  ");
            Cubios::GFX_drawText(120, 90, 8, 0, Cubios::text_align_t::TEXT_ALIGN_CENTER, Cubios::Gfx::Colors::white, " /__\\ ");
            Cubios::GFX_drawText(120, 100, 8, 0, Cubios::text_align_t::TEXT_ALIGN_CENTER, Cubios::Gfx::Colors::white, "|FARM|");
        }

        // 3. Top Fence
        Cubios::GFX_drawText(120, 25, 8, 0, Cubios::text_align_t::TEXT_ALIGN_CENTER, Cubios::Gfx::Colors::white, "===================================");

        // COOLDOWN INDICATOR
        if (twistCooldown > 0)
        {
            int secondsLeft = (twistCooldown + 999) / 1000; 
            std::string waitStr = "WAIT: " + std::to_string(secondsLeft) + "s";
            
            Cubios::GFX_drawText(120, 45, 8, 0, Cubios::text_align_t::TEXT_ALIGN_CENTER, Cubios::Gfx::Colors::magenta, waitStr.c_str());
        }

        // 4. THE 3-STATE BOTTOM FENCE
        if (fenceState[screenID] == 1)
        {
            // State 1: Broken Gap
            Cubios::GFX_drawText(120, 230, 8, 0, Cubios::text_align_t::TEXT_ALIGN_CENTER, Cubios::Gfx::Colors::red, "[==    GAP    ==]");
        }
        else if (fenceState[screenID] == 2)
        {
            // State 2: Patched
            Cubios::GFX_drawText(120, 230, 8, 0, Cubios::text_align_t::TEXT_ALIGN_CENTER, Cubios::Gfx::Colors::blue, "[++++ PATCHED ++++]");
        }
        else
        {
            // State 0: Normal Safe Wall
            Cubios::GFX_drawText(120, 230, 8, 0, Cubios::text_align_t::TEXT_ALIGN_CENTER, Cubios::Gfx::Colors::white, "[====================]");
        }

        // 5. Draw the Animated Chicken
        for (int c = 0; c < 3; c++)
        {
            if (chickens[c].currentScreen == screenID)
            {
                const char *frame = ((gameTime / 250) % 2 == 0) ? "\\(o)/" : "/(o)\\";
                
                // Show a pecking/standing sprite if stationary
                if (chickens[c].speedX == 0 && chickens[c].speedY == 0) 
                {
                    frame = "-(o)-";
                }

                Cubios::GFX_drawText(chickens[c].x, chickens[c].y, 8, 0,
                                     Cubios::text_align_t::TEXT_ALIGN_CENTER,
                                     Cubios::Gfx::Colors::yellow, frame);
            }
        }

        Cubios::GFX_render();
    }
}

// ==========================================
// CONTROLS (THE NATIVE ACTION)
// ==========================================

void farmEscape::on_Twist(const Cubios::TOPOLOGY_twistInfo_t &twist)
{
    // 1. GAME OVER RESET
    if (lives <= 0)
    {
        lives = 5;
        currentRound = 1;
        score = 0;
        breakInterval = 7000;
        breakTimer = 0;
        scoreTimer = 0;
        twistCooldown = 0; // Reset cooldown
        
        // Reset all three chickens to their starting states
        chickens[0] = {60, 100, 4, 3, 0, 2000};
        chickens[1] = {120, 120, -5, 4, 1, 1500};
        chickens[2] = {180, 80, 3, -2, 2, 2800};
        
        fenceState[0] = 0;
        fenceState[1] = 0;
        fenceState[2] = 0;
        return;
    }

    // Check if the cooldown is active
    if (twistCooldown > 0)
    {
        // Still on cooldown! Ignore the twist.
        return; 
    }

    // 2. MASS REPAIR (OS Update Fix)
    // Fixes ALL broken fences on the cube at once.
    bool repairedSomething = false;
    for (int screenID = 0; screenID < 3; screenID++)
    {
        if (fenceState[screenID] == 1)
        {
            fenceState[screenID] = 2; // Patch it!
            repairedSomething = true; // We successfully fixed at least one fence
        }
    }

    // Only apply the cooldown if we actually fixed something
    if (repairedSomething)
    {
        twistCooldown = 3000;
    }
}

void farmEscape::on_Pat(uint32_t count)
{
    if (lives <= 0)
    {
        lives = 5;
        currentRound = 1;
        score = 0;
        breakInterval = 7000;
        breakTimer = 0;
        scoreTimer = 0;
        twistCooldown = 0;
        
        chickens[0] = {60, 100, 4, 3, 0, 2000};
        chickens[1] = {120, 120, -5, 4, 1, 1500};
        chickens[2] = {180, 80, 3, -2, 2, 2800};
        
        fenceState[0] = 0;
        fenceState[1] = 0;
        fenceState[2] = 0;
        return;
    }

    // Change any Broken fence (1) into a Patched fence (2) by PROXIMITY CHECK
    for (int c = 0; c < 3; c++)
    {
        int activeScreen = chickens[c].currentScreen;
        if (fenceState[activeScreen] == 1)
        {
            fenceState[activeScreen] = 2;
        }
    }
}

// Unused Callbacks
void farmEscape::on_PhysicsTick(const std::array<Cubios::Screen, 3> &screens) {}
void farmEscape::on_Timer(uint8_t timerID) {}
void farmEscape::on_Message(uint32_t type, uint8_t *pkt, u32_t size) {}
void farmEscape::on_ExternalMessage(uint8_t *pkt, u32_t size) {}
void farmEscape::on_Close() {}
void farmEscape::drawModuleNumber() {}