// This header file is generated by WOWCube SDK project wizard
//
// Application UUID: Gkgjdbq0qp
//
#pragma once
#include "Gfx.h"

class farmEscape: public Cubios::Application 
{
public:
    farmEscape();
    virtual ~farmEscape();

    virtual void on_PhysicsTick(const std::array<Cubios::Screen, 3>& screens) override;
    virtual void on_Twist(const Cubios::TOPOLOGY_twistInfo_t& twist) override;
    virtual void on_Message(uint32_t type, uint8_t* pkt, u32_t size) override;
    virtual void on_ExternalMessage(uint8_t* pkt, u32_t size) override;
    virtual void on_Pat(uint32_t count) override;
    virtual void on_Render(std::array<Cubios::Screen, 3>& screens) override;
    virtual void on_Tick(uint32_t currentTime, uint32_t deltaTime) override;
    virtual void on_Timer(uint8_t timerID) override;
    virtual void on_Close() override;

private:
    static void drawModuleNumber();
};